/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as FoodIdRouteImport } from './routes/food.$id'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutAddressRouteImport } from './routes/checkout.address'
import { Route as CategoryIdRouteImport } from './routes/category.$id'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrdersRoute,
} as any)
const FoodIdRoute = FoodIdRouteImport.update({
  id: '/food/$id',
  path: '/food/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutAddressRoute = CheckoutAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => CheckoutRoute,
} as any)
const CategoryIdRoute = CategoryIdRouteImport.update({
  id: '/category/$id',
  path: '/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/category/$id': typeof CategoryIdRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/food/$id': typeof FoodIdRoute
  '/orders/$id': typeof OrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/category/$id': typeof CategoryIdRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/food/$id': typeof FoodIdRoute
  '/orders/$id': typeof OrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cards': typeof CardsRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/favorites': typeof FavoritesRoute
  '/home': typeof HomeRoute
  '/loyalty': typeof LoyaltyRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/reservation': typeof ReservationRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/category/$id': typeof CategoryIdRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/food/$id': typeof FoodIdRoute
  '/orders/$id': typeof OrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cards'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/loyalty'
    | '/notifications'
    | '/offers'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reservation'
    | '/search'
    | '/settings'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/category/$id'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/success'
    | '/food/$id'
    | '/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cards'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/loyalty'
    | '/notifications'
    | '/offers'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reservation'
    | '/search'
    | '/settings'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/category/$id'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/success'
    | '/food/$id'
    | '/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/cards'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/favorites'
    | '/home'
    | '/loyalty'
    | '/notifications'
    | '/offers'
    | '/onboarding'
    | '/orders'
    | '/profile'
    | '/reservation'
    | '/search'
    | '/settings'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/category/$id'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/success'
    | '/food/$id'
    | '/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CardsRoute: typeof CardsRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  FavoritesRoute: typeof FavoritesRoute
  HomeRoute: typeof HomeRoute
  LoyaltyRoute: typeof LoyaltyRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReservationRoute: typeof ReservationRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  CategoryIdRoute: typeof CategoryIdRoute
  FoodIdRoute: typeof FoodIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/food/$id': {
      id: '/food/$id'
      path: '/food/$id'
      fullPath: '/food/$id'
      preLoaderRoute: typeof FoodIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/address': {
      id: '/checkout/address'
      path: '/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof CheckoutAddressRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/category/$id': {
      id: '/category/$id'
      path: '/category/$id'
      fullPath: '/category/$id'
      preLoaderRoute: typeof CategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutAddressRoute: typeof CheckoutAddressRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutAddressRoute: CheckoutAddressRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface OrdersRouteChildren {
  OrdersIdRoute: typeof OrdersIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersIdRoute: OrdersIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CardsRoute: CardsRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  FavoritesRoute: FavoritesRoute,
  HomeRoute: HomeRoute,
  LoyaltyRoute: LoyaltyRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReservationRoute: ReservationRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CategoryIdRoute: CategoryIdRoute,
  FoodIdRoute: FoodIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
