/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSupportRouteImport } from './routes/app.support'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppEarningsRouteImport } from './routes/app.earnings'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppOrdersIndexRouteImport } from './routes/app.orders.index'
import { Route as AppOrdersIdRouteImport } from './routes/app.orders.$id'
import { Route as AppOrdersIdSuccessRouteImport } from './routes/app.orders.$id.success'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEarningsRoute = AppEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdSuccessRoute = AppOrdersIdSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => AppOrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/orders/$id': typeof AppOrdersIdRouteWithChildren
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/orders/$id/success': typeof AppOrdersIdSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/orders/$id': typeof AppOrdersIdRouteWithChildren
  '/app/orders': typeof AppOrdersIndexRoute
  '/app/orders/$id/success': typeof AppOrdersIdSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/earnings': typeof AppEarningsRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/support': typeof AppSupportRoute
  '/app/orders/$id': typeof AppOrdersIdRouteWithChildren
  '/app/orders/': typeof AppOrdersIndexRoute
  '/app/orders/$id/success': typeof AppOrdersIdSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/earnings'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/support'
    | '/app/orders/$id'
    | '/app/orders/'
    | '/app/orders/$id/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/earnings'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/support'
    | '/app/orders/$id'
    | '/app/orders'
    | '/app/orders/$id/success'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/dashboard'
    | '/app/earnings'
    | '/app/history'
    | '/app/notifications'
    | '/app/profile'
    | '/app/settings'
    | '/app/support'
    | '/app/orders/$id'
    | '/app/orders/'
    | '/app/orders/$id/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/support': {
      id: '/app/support'
      path: '/support'
      fullPath: '/app/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/earnings': {
      id: '/app/earnings'
      path: '/earnings'
      fullPath: '/app/earnings'
      preLoaderRoute: typeof AppEarningsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/': {
      id: '/app/orders/'
      path: '/orders'
      fullPath: '/app/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$id': {
      id: '/app/orders/$id'
      path: '/orders/$id'
      fullPath: '/app/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/orders/$id/success': {
      id: '/app/orders/$id/success'
      path: '/success'
      fullPath: '/app/orders/$id/success'
      preLoaderRoute: typeof AppOrdersIdSuccessRouteImport
      parentRoute: typeof AppOrdersIdRoute
    }
  }
}

interface AppOrdersIdRouteChildren {
  AppOrdersIdSuccessRoute: typeof AppOrdersIdSuccessRoute
}

const AppOrdersIdRouteChildren: AppOrdersIdRouteChildren = {
  AppOrdersIdSuccessRoute: AppOrdersIdSuccessRoute,
}

const AppOrdersIdRouteWithChildren = AppOrdersIdRoute._addFileChildren(
  AppOrdersIdRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEarningsRoute: typeof AppEarningsRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppOrdersIdRoute: typeof AppOrdersIdRouteWithChildren
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEarningsRoute: AppEarningsRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSupportRoute: AppSupportRoute,
  AppOrdersIdRoute: AppOrdersIdRouteWithChildren,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
