import type { Order, Rider, NotificationItemData } from "@/types";

export const mockRider: Rider = {
  id: "r_001",
  name: "Kasun Perera",
  phone: "+94 77 123 4567",
  email: "kasun@happyhome.lk",
  vehicle: { type: "scooter", plate: "WP CAB-4421" },
  rating: 4.9,
  totalDeliveries: 1284,
  online: true,
};

export const mockOrders: Order[] = [
  {
    id: "o1",
    code: "HH1024",
    status: "ready_for_pickup",
    items: [
      { id: "i1", name: "Chicken Kottu", quantity: 2, price: 1200 },
      { id: "i2", name: "Butter Chicken", quantity: 1, price: 1850 },
      { id: "i3", name: "Mojito", quantity: 3, price: 550 },
    ],
    customer: {
      id: "c1",
      name: "Nimali Fernando",
      phone: "+94 71 902 3344",
      address: "24/B Park Street, Colombo 02",
      notes: "Apartment 4B. Ring the bell twice.",
      lat: 6.9215,
      lng: 79.857,
    },
    subtotal: 5900,
    deliveryFee: 350,
    riderEarning: 280,
    distanceKm: 3.2,
    etaMinutes: 18,
    createdAt: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    paymentMethod: "cash",
  },
  {
    id: "o2",
    code: "HH1025",
    status: "pending",
    items: [
      { id: "i4", name: "Mixed Fried Rice", quantity: 1, price: 1100 },
      { id: "i5", name: "Shawarma", quantity: 2, price: 850 },
      { id: "i6", name: "Faluda", quantity: 2, price: 650 },
    ],
    customer: {
      id: "c2",
      name: "Ravindu Jayasinghe",
      phone: "+94 76 441 8821",
      address: "18 Marine Drive, Bambalapitiya",
      notes: "Leave at the security desk.",
      lat: 6.892,
      lng: 79.853,
    },
    subtotal: 4100,
    deliveryFee: 320,
    riderEarning: 260,
    distanceKm: 2.4,
    etaMinutes: 14,
    createdAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    paymentMethod: "online",
  },
  {
    id: "o3",
    code: "HH1026",
    status: "pending",
    items: [
      { id: "i7", name: "Devilled Prawns", quantity: 1, price: 2100 },
      { id: "i8", name: "Egg Fried Rice", quantity: 2, price: 950 },
      { id: "i9", name: "King Coconut", quantity: 2, price: 280 },
    ],
    customer: {
      id: "c3",
      name: "Sahan Bandara",
      phone: "+94 70 113 2211",
      address: "62 Horton Place, Colombo 07",
      lat: 6.91,
      lng: 79.87,
    },
    subtotal: 4560,
    deliveryFee: 420,
    riderEarning: 340,
    distanceKm: 4.6,
    etaMinutes: 22,
    createdAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    paymentMethod: "card",
  },
];

export const mockHistory: Order[] = [
  {
    id: "h1",
    code: "HH1018",
    status: "delivered",
    items: [
      { id: "x1", name: "Cheese Kottu", quantity: 1, price: 1400 },
      { id: "x2", name: "Watalappan", quantity: 2, price: 600 },
    ],
    customer: {
      id: "c4",
      name: "Tharushi Silva",
      phone: "+94 77 887 6655",
      address: "11 Flower Rd, Colombo 07",
      lat: 6.91, lng: 79.86,
    },
    subtotal: 2600, deliveryFee: 300, riderEarning: 240,
    distanceKm: 2.1, etaMinutes: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 2.6).toISOString(),
    paymentMethod: "cash",
  },
  {
    id: "h2",
    code: "HH1015",
    status: "delivered",
    items: [{ id: "x3", name: "Biryani Platter", quantity: 2, price: 1900 }],
    customer: {
      id: "c5",
      name: "Asela Wickrama",
      phone: "+94 76 221 9988",
      address: "5 Reid Ave, Colombo 04",
      lat: 6.9, lng: 79.86,
    },
    subtotal: 3800, deliveryFee: 280, riderEarning: 220,
    distanceKm: 1.8, etaMinutes: 10,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 4.7).toISOString(),
    paymentMethod: "online",
  },
  {
    id: "h3",
    code: "HH1009",
    status: "delivered",
    items: [{ id: "x4", name: "Paneer Tikka", quantity: 1, price: 1650 }],
    customer: {
      id: "c6",
      name: "Mihiri Rathnayake",
      phone: "+94 71 552 3311",
      address: "78 Duplication Rd, Colombo 03",
      lat: 6.89, lng: 79.85,
    },
    subtotal: 1650, deliveryFee: 250, riderEarning: 200,
    distanceKm: 1.4, etaMinutes: 9,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    deliveredAt: new Date(Date.now() - 1000 * 60 * 60 * 25.8).toISOString(),
    paymentMethod: "cash",
  },
];

export const mockNotifications: NotificationItemData[] = [
  { id: "n1", type: "order", title: "New order assigned", message: "Order #HH1025 is ready for pickup.", time: "2m ago", read: false },
  { id: "n2", type: "earning", title: "Payout processed", message: "LKR 4,820 credited to your account.", time: "1h ago", read: false },
  { id: "n3", type: "system", title: "Shift reminder", message: "Your evening shift starts at 5:00 PM.", time: "3h ago", read: true },
  { id: "n4", type: "alert", title: "Heavy rain alert", message: "Drive carefully in the Colombo 03 area.", time: "Yesterday", read: true },
];

export const earningsSummary = {
  today: 2840,
  week: 18420,
  month: 72380,
  trips: { today: 11, week: 64, month: 248 },
  tips: 1240,
  hours: 6.5,
  weekly: [1800, 2400, 1950, 3100, 2840, 3200, 3130],
};
