/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardSupportRouteImport } from './routes/_dashboard/support'
import { Route as DashboardRidersRouteImport } from './routes/_dashboard/riders'
import { Route as DashboardReservationsRouteImport } from './routes/_dashboard/reservations'
import { Route as DashboardPromotionsRouteImport } from './routes/_dashboard/promotions'
import { Route as DashboardOrdersRouteImport } from './routes/_dashboard/orders'
import { Route as DashboardNotificationsRouteImport } from './routes/_dashboard/notifications'
import { Route as DashboardMenuRouteImport } from './routes/_dashboard/menu'
import { Route as DashboardLoyaltyRouteImport } from './routes/_dashboard/loyalty'
import { Route as DashboardKitchenRouteImport } from './routes/_dashboard/kitchen'
import { Route as DashboardInventoryRouteImport } from './routes/_dashboard/inventory'
import { Route as DashboardFeedbackRouteImport } from './routes/_dashboard/feedback'
import { Route as DashboardDeliveryRouteImport } from './routes/_dashboard/delivery'
import { Route as DashboardCustomersRouteImport } from './routes/_dashboard/customers'
import { Route as DashboardAnalyticsRouteImport } from './routes/_dashboard/analytics'
import { Route as DashboardActivityRouteImport } from './routes/_dashboard/activity'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard/settings.index'
import { Route as DashboardSettingsSystemRouteImport } from './routes/_dashboard/settings.system'
import { Route as DashboardSettingsStaffRouteImport } from './routes/_dashboard/settings.staff'
import { Route as DashboardSettingsProfileRouteImport } from './routes/_dashboard/settings.profile'
import { Route as DashboardSettingsDeliveryRadiusRouteImport } from './routes/_dashboard/settings.delivery-radius'
import { Route as DashboardReportsRevenueRouteImport } from './routes/_dashboard/reports.revenue'
import { Route as DashboardReportsPaymentsRouteImport } from './routes/_dashboard/reports.payments'
import { Route as DashboardReportsCodCardRouteImport } from './routes/_dashboard/reports.cod-card'
import { Route as DashboardMenuNewRouteImport } from './routes/_dashboard/menu.new'
import { Route as DashboardMenuCategoriesRouteImport } from './routes/_dashboard/menu.categories'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportRoute = DashboardSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRidersRoute = DashboardRidersRouteImport.update({
  id: '/riders',
  path: '/riders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReservationsRoute = DashboardReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPromotionsRoute = DashboardPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoyaltyRoute = DashboardLoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKitchenRoute = DashboardKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInventoryRoute = DashboardInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFeedbackRoute = DashboardFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeliveryRoute = DashboardDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsSystemRoute = DashboardSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsStaffRoute = DashboardSettingsStaffRouteImport.update({
  id: '/settings/staff',
  path: '/settings/staff',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsProfileRoute =
  DashboardSettingsProfileRouteImport.update({
    id: '/settings/profile',
    path: '/settings/profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSettingsDeliveryRadiusRoute =
  DashboardSettingsDeliveryRadiusRouteImport.update({
    id: '/settings/delivery-radius',
    path: '/settings/delivery-radius',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsRevenueRoute = DashboardReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsPaymentsRoute =
  DashboardReportsPaymentsRouteImport.update({
    id: '/reports/payments',
    path: '/reports/payments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsCodCardRoute = DashboardReportsCodCardRouteImport.update({
  id: '/reports/cod-card',
  path: '/reports/cod-card',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuNewRoute = DashboardMenuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardMenuRoute,
} as any)
const DashboardMenuCategoriesRoute = DashboardMenuCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardMenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/activity': typeof DashboardActivityRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/customers': typeof DashboardCustomersRoute
  '/delivery': typeof DashboardDeliveryRoute
  '/feedback': typeof DashboardFeedbackRoute
  '/inventory': typeof DashboardInventoryRoute
  '/kitchen': typeof DashboardKitchenRoute
  '/loyalty': typeof DashboardLoyaltyRoute
  '/menu': typeof DashboardMenuRouteWithChildren
  '/notifications': typeof DashboardNotificationsRoute
  '/orders': typeof DashboardOrdersRoute
  '/promotions': typeof DashboardPromotionsRoute
  '/reservations': typeof DashboardReservationsRoute
  '/riders': typeof DashboardRidersRoute
  '/support': typeof DashboardSupportRoute
  '/menu/categories': typeof DashboardMenuCategoriesRoute
  '/menu/new': typeof DashboardMenuNewRoute
  '/reports/cod-card': typeof DashboardReportsCodCardRoute
  '/reports/payments': typeof DashboardReportsPaymentsRoute
  '/reports/revenue': typeof DashboardReportsRevenueRoute
  '/settings/delivery-radius': typeof DashboardSettingsDeliveryRadiusRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/staff': typeof DashboardSettingsStaffRoute
  '/settings/system': typeof DashboardSettingsSystemRoute
  '/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/activity': typeof DashboardActivityRoute
  '/analytics': typeof DashboardAnalyticsRoute
  '/customers': typeof DashboardCustomersRoute
  '/delivery': typeof DashboardDeliveryRoute
  '/feedback': typeof DashboardFeedbackRoute
  '/inventory': typeof DashboardInventoryRoute
  '/kitchen': typeof DashboardKitchenRoute
  '/loyalty': typeof DashboardLoyaltyRoute
  '/menu': typeof DashboardMenuRouteWithChildren
  '/notifications': typeof DashboardNotificationsRoute
  '/orders': typeof DashboardOrdersRoute
  '/promotions': typeof DashboardPromotionsRoute
  '/reservations': typeof DashboardReservationsRoute
  '/riders': typeof DashboardRidersRoute
  '/support': typeof DashboardSupportRoute
  '/': typeof DashboardIndexRoute
  '/menu/categories': typeof DashboardMenuCategoriesRoute
  '/menu/new': typeof DashboardMenuNewRoute
  '/reports/cod-card': typeof DashboardReportsCodCardRoute
  '/reports/payments': typeof DashboardReportsPaymentsRoute
  '/reports/revenue': typeof DashboardReportsRevenueRoute
  '/settings/delivery-radius': typeof DashboardSettingsDeliveryRadiusRoute
  '/settings/profile': typeof DashboardSettingsProfileRoute
  '/settings/staff': typeof DashboardSettingsStaffRoute
  '/settings/system': typeof DashboardSettingsSystemRoute
  '/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/_dashboard/activity': typeof DashboardActivityRoute
  '/_dashboard/analytics': typeof DashboardAnalyticsRoute
  '/_dashboard/customers': typeof DashboardCustomersRoute
  '/_dashboard/delivery': typeof DashboardDeliveryRoute
  '/_dashboard/feedback': typeof DashboardFeedbackRoute
  '/_dashboard/inventory': typeof DashboardInventoryRoute
  '/_dashboard/kitchen': typeof DashboardKitchenRoute
  '/_dashboard/loyalty': typeof DashboardLoyaltyRoute
  '/_dashboard/menu': typeof DashboardMenuRouteWithChildren
  '/_dashboard/notifications': typeof DashboardNotificationsRoute
  '/_dashboard/orders': typeof DashboardOrdersRoute
  '/_dashboard/promotions': typeof DashboardPromotionsRoute
  '/_dashboard/reservations': typeof DashboardReservationsRoute
  '/_dashboard/riders': typeof DashboardRidersRoute
  '/_dashboard/support': typeof DashboardSupportRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/menu/categories': typeof DashboardMenuCategoriesRoute
  '/_dashboard/menu/new': typeof DashboardMenuNewRoute
  '/_dashboard/reports/cod-card': typeof DashboardReportsCodCardRoute
  '/_dashboard/reports/payments': typeof DashboardReportsPaymentsRoute
  '/_dashboard/reports/revenue': typeof DashboardReportsRevenueRoute
  '/_dashboard/settings/delivery-radius': typeof DashboardSettingsDeliveryRadiusRoute
  '/_dashboard/settings/profile': typeof DashboardSettingsProfileRoute
  '/_dashboard/settings/staff': typeof DashboardSettingsStaffRoute
  '/_dashboard/settings/system': typeof DashboardSettingsSystemRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity'
    | '/analytics'
    | '/customers'
    | '/delivery'
    | '/feedback'
    | '/inventory'
    | '/kitchen'
    | '/loyalty'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/promotions'
    | '/reservations'
    | '/riders'
    | '/support'
    | '/menu/categories'
    | '/menu/new'
    | '/reports/cod-card'
    | '/reports/payments'
    | '/reports/revenue'
    | '/settings/delivery-radius'
    | '/settings/profile'
    | '/settings/staff'
    | '/settings/system'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/activity'
    | '/analytics'
    | '/customers'
    | '/delivery'
    | '/feedback'
    | '/inventory'
    | '/kitchen'
    | '/loyalty'
    | '/menu'
    | '/notifications'
    | '/orders'
    | '/promotions'
    | '/reservations'
    | '/riders'
    | '/support'
    | '/'
    | '/menu/categories'
    | '/menu/new'
    | '/reports/cod-card'
    | '/reports/payments'
    | '/reports/revenue'
    | '/settings/delivery-radius'
    | '/settings/profile'
    | '/settings/staff'
    | '/settings/system'
    | '/settings'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/_dashboard/activity'
    | '/_dashboard/analytics'
    | '/_dashboard/customers'
    | '/_dashboard/delivery'
    | '/_dashboard/feedback'
    | '/_dashboard/inventory'
    | '/_dashboard/kitchen'
    | '/_dashboard/loyalty'
    | '/_dashboard/menu'
    | '/_dashboard/notifications'
    | '/_dashboard/orders'
    | '/_dashboard/promotions'
    | '/_dashboard/reservations'
    | '/_dashboard/riders'
    | '/_dashboard/support'
    | '/_dashboard/'
    | '/_dashboard/menu/categories'
    | '/_dashboard/menu/new'
    | '/_dashboard/reports/cod-card'
    | '/_dashboard/reports/payments'
    | '/_dashboard/reports/revenue'
    | '/_dashboard/settings/delivery-radius'
    | '/_dashboard/settings/profile'
    | '/_dashboard/settings/staff'
    | '/_dashboard/settings/system'
    | '/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/support': {
      id: '/_dashboard/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof DashboardSupportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/riders': {
      id: '/_dashboard/riders'
      path: '/riders'
      fullPath: '/riders'
      preLoaderRoute: typeof DashboardRidersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reservations': {
      id: '/_dashboard/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof DashboardReservationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/promotions': {
      id: '/_dashboard/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof DashboardPromotionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/orders': {
      id: '/_dashboard/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/notifications': {
      id: '/_dashboard/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/menu': {
      id: '/_dashboard/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/loyalty': {
      id: '/_dashboard/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof DashboardLoyaltyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/kitchen': {
      id: '/_dashboard/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof DashboardKitchenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/inventory': {
      id: '/_dashboard/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof DashboardInventoryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/feedback': {
      id: '/_dashboard/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof DashboardFeedbackRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/delivery': {
      id: '/_dashboard/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DashboardDeliveryRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/customers': {
      id: '/_dashboard/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/analytics': {
      id: '/_dashboard/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/activity': {
      id: '/_dashboard/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/system': {
      id: '/_dashboard/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof DashboardSettingsSystemRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/staff': {
      id: '/_dashboard/settings/staff'
      path: '/settings/staff'
      fullPath: '/settings/staff'
      preLoaderRoute: typeof DashboardSettingsStaffRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/profile': {
      id: '/_dashboard/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof DashboardSettingsProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/delivery-radius': {
      id: '/_dashboard/settings/delivery-radius'
      path: '/settings/delivery-radius'
      fullPath: '/settings/delivery-radius'
      preLoaderRoute: typeof DashboardSettingsDeliveryRadiusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/revenue': {
      id: '/_dashboard/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof DashboardReportsRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/payments': {
      id: '/_dashboard/reports/payments'
      path: '/reports/payments'
      fullPath: '/reports/payments'
      preLoaderRoute: typeof DashboardReportsPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports/cod-card': {
      id: '/_dashboard/reports/cod-card'
      path: '/reports/cod-card'
      fullPath: '/reports/cod-card'
      preLoaderRoute: typeof DashboardReportsCodCardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/menu/new': {
      id: '/_dashboard/menu/new'
      path: '/new'
      fullPath: '/menu/new'
      preLoaderRoute: typeof DashboardMenuNewRouteImport
      parentRoute: typeof DashboardMenuRoute
    }
    '/_dashboard/menu/categories': {
      id: '/_dashboard/menu/categories'
      path: '/categories'
      fullPath: '/menu/categories'
      preLoaderRoute: typeof DashboardMenuCategoriesRouteImport
      parentRoute: typeof DashboardMenuRoute
    }
  }
}

interface DashboardMenuRouteChildren {
  DashboardMenuCategoriesRoute: typeof DashboardMenuCategoriesRoute
  DashboardMenuNewRoute: typeof DashboardMenuNewRoute
}

const DashboardMenuRouteChildren: DashboardMenuRouteChildren = {
  DashboardMenuCategoriesRoute: DashboardMenuCategoriesRoute,
  DashboardMenuNewRoute: DashboardMenuNewRoute,
}

const DashboardMenuRouteWithChildren = DashboardMenuRoute._addFileChildren(
  DashboardMenuRouteChildren,
)

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDeliveryRoute: typeof DashboardDeliveryRoute
  DashboardFeedbackRoute: typeof DashboardFeedbackRoute
  DashboardInventoryRoute: typeof DashboardInventoryRoute
  DashboardKitchenRoute: typeof DashboardKitchenRoute
  DashboardLoyaltyRoute: typeof DashboardLoyaltyRoute
  DashboardMenuRoute: typeof DashboardMenuRouteWithChildren
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPromotionsRoute: typeof DashboardPromotionsRoute
  DashboardReservationsRoute: typeof DashboardReservationsRoute
  DashboardRidersRoute: typeof DashboardRidersRoute
  DashboardSupportRoute: typeof DashboardSupportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReportsCodCardRoute: typeof DashboardReportsCodCardRoute
  DashboardReportsPaymentsRoute: typeof DashboardReportsPaymentsRoute
  DashboardReportsRevenueRoute: typeof DashboardReportsRevenueRoute
  DashboardSettingsDeliveryRadiusRoute: typeof DashboardSettingsDeliveryRadiusRoute
  DashboardSettingsProfileRoute: typeof DashboardSettingsProfileRoute
  DashboardSettingsStaffRoute: typeof DashboardSettingsStaffRoute
  DashboardSettingsSystemRoute: typeof DashboardSettingsSystemRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDeliveryRoute: DashboardDeliveryRoute,
  DashboardFeedbackRoute: DashboardFeedbackRoute,
  DashboardInventoryRoute: DashboardInventoryRoute,
  DashboardKitchenRoute: DashboardKitchenRoute,
  DashboardLoyaltyRoute: DashboardLoyaltyRoute,
  DashboardMenuRoute: DashboardMenuRouteWithChildren,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPromotionsRoute: DashboardPromotionsRoute,
  DashboardReservationsRoute: DashboardReservationsRoute,
  DashboardRidersRoute: DashboardRidersRoute,
  DashboardSupportRoute: DashboardSupportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReportsCodCardRoute: DashboardReportsCodCardRoute,
  DashboardReportsPaymentsRoute: DashboardReportsPaymentsRoute,
  DashboardReportsRevenueRoute: DashboardReportsRevenueRoute,
  DashboardSettingsDeliveryRadiusRoute: DashboardSettingsDeliveryRadiusRoute,
  DashboardSettingsProfileRoute: DashboardSettingsProfileRoute,
  DashboardSettingsStaffRoute: DashboardSettingsStaffRoute,
  DashboardSettingsSystemRoute: DashboardSettingsSystemRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
